Exception ignored in: <bound method MinionSol.__del__ of <minion.MinionSol object at 0x2b8bff2dc748>>
Traceback (most recent call last):
  File "/home/pventura/relationaldef/minion.py", line 136, in __del__
    if not self.EOF:
AttributeError: 'MinionSol' object has no attribute 'EOF'
Spectrum = [3, 2, 1]
CANCELLED

State before abort: 
  Diversity = 2598
    1-diversity = 2
    2-diversity = 37
    3-diversity = 2559
  #Auts = 57
  #Isos = 7245
  1400765 calls to Minion

 Performance counter stats for 'timeout --signal=SIGINT 45m python3 ../../relationaldef/main.py':

    2966295.845420      task-clock (msec)         #    1.099 CPUs utilized          
         6,208,093      context-switches          #    0.002 M/sec                  
           367,879      cpu-migrations            #    0.124 K/sec                  
       586,080,519      page-faults               #    0.198 M/sec                  
 7,792,105,554,248      cycles                    #    2.627 GHz                    
 5,546,379,829,429      instructions              #    0.71  insn per cycle         
 1,139,615,476,086      branches                  #  384.188 M/sec                  
    28,291,512,744      branch-misses             #    2.48% of all branches        

    2700.040261865 seconds time elapsed

