Exception ignored in: <bound method Popen.__del__ of <subprocess.Popen object at 0x2aeab0deff98>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/subprocess.py", line 768, in __del__
    self._internal_poll(_deadstate=_maxsize)
KeyboardInterrupt
Spectrum = [3, 2, 1]
DEFINABLE

Final state: 
  Diversity = 9926
    1-diversity = 2
    2-diversity = 115
    3-diversity = 9809
  #Auts = 25
  #Isos = 773
  5800123 calls to Minion

 Performance counter stats for 'timeout --signal=SIGINT 45m python3 ../../relationaldef/main.py':

   16313750.177771      task-clock (msec)         #    1.076 CPUs utilized          
        25,570,686      context-switches          #    0.002 M/sec                  
         1,727,349      cpu-migrations            #    0.106 K/sec                  
     2,613,096,756      page-faults               #    0.160 M/sec                  
42,586,573,704,029      cycles                    #    2.610 GHz                    
30,478,063,832,871      instructions              #    0.72  insn per cycle         
 6,192,578,102,012      branches                  #  379.593 M/sec                  
   128,448,467,124      branch-misses             #    2.07% of all branches        

   15158.968457878 seconds time elapsed

