Exception ignored in: <bound method MinionSol.__del__ of <minion.MinionSol object at 0x14cdb2254fd0>>
Traceback (most recent call last):
  File "/home/pventura/relationaldef/minion.py", line 136, in __del__
    if not self.EOF:
AttributeError: 'MinionSol' object has no attribute 'EOF'
Spectrum = [3, 2, 1]
CANCELLED

State before abort: 
  Diversity = 2392
    1-diversity = 2
    2-diversity = 35
    3-diversity = 2355
  #Auts = 62
  #Isos = 5800
  1117765 calls to Minion

 Performance counter stats for 'timeout --signal=SIGINT 45m python3 ../../relationaldef/main.py':

    2515823.041429      task-clock (msec)         #    0.932 CPUs utilized          
         6,126,082      context-switches          #    0.002 M/sec                  
         2,388,594      cpu-migrations            #    0.949 K/sec                  
       441,560,582      page-faults               #    0.176 M/sec                  
 6,493,328,863,069      cycles                    #    2.581 GHz                    
 3,895,727,518,765      instructions              #    0.60  insn per cycle         
   799,928,709,015      branches                  #  317.959 M/sec                  
    20,755,697,099      branch-misses             #    2.59% of all branches        

    2700.037791479 seconds time elapsed

