Exception ignored in: <bound method MinionSol.__del__ of <minion.MinionSol object at 0x14665634df60>>
Traceback (most recent call last):
  File "/home/pventura/relationaldef/minion.py", line 136, in __del__
    if not self.EOF:
AttributeError: 'MinionSol' object has no attribute 'EOF'
Spectrum = [3, 2, 1]
CANCELLED

State before abort: 
  Diversity = 4165
    1-diversity = 2
    2-diversity = 131
    3-diversity = 4032
  #Auts = 18
  #Isos = 686
  932307 calls to Minion

 Performance counter stats for 'timeout --signal=SIGINT 45m python3 ../../relationaldef/main.py':

    2546795.837948      task-clock (msec)         #    0.943 CPUs utilized          
         5,159,787      context-switches          #    0.002 M/sec                  
         2,135,079      cpu-migrations            #    0.838 K/sec                  
       388,893,350      page-faults               #    0.153 M/sec                  
 6,563,876,032,947      cycles                    #    2.577 GHz                    
 4,947,193,335,231      instructions              #    0.75  insn per cycle         
 1,009,807,433,947      branches                  #  396.501 M/sec                  
    19,480,574,717      branch-misses             #    1.93% of all branches        

    2700.076278867 seconds time elapsed

