Exception ignored in: <bound method MinionSol.__del__ of <minion.MinionSol object at 0x1514f2d39860>>
Traceback (most recent call last):
  File "/home/pventura/relationaldef/minion.py", line 136, in __del__
    if not self.EOF:
AttributeError: 'MinionSol' object has no attribute 'EOF'
Spectrum = [3, 2, 1]
CANCELLED

State before abort: 
  Diversity = 1144
    1-diversity = 2
    2-diversity = 43
    3-diversity = 1099
  #Auts = 29
  #Isos = 2308
  220719 calls to Minion

 Performance counter stats for 'timeout --signal=SIGINT 45m python3 ../../relationaldef/main.py':

     461165.760113      task-clock (msec)         #    0.171 CPUs utilized          
         1,512,796      context-switches          #    0.003 M/sec                  
           296,011      cpu-migrations            #    0.642 K/sec                  
        93,166,465      page-faults               #    0.202 M/sec                  
 1,192,863,912,085      cycles                    #    2.587 GHz                    
   859,865,869,450      instructions              #    0.72  insn per cycle         
   176,181,419,820      branches                  #  382.035 M/sec                  
     4,271,372,466      branch-misses             #    2.42% of all branches        

    2700.082929840 seconds time elapsed

