Exception ignored in: <bound method MinionSol.__del__ of <minion.MinionSol object at 0x2b5ef1d54a20>>
Traceback (most recent call last):
  File "/home/pventura/relationaldef/minion.py", line 128, in __del__
    def __del__(self):
KeyboardInterrupt
Spectrum=[3, 2, 1]
Diversity=3090
1-diversity=2
2-diversity=43
3-diversity=3045
#Auts=3151
#Isos=12676
1445202 calls to Minion
DEFINABLE

 Performance counter stats for 'timeout --signal=SIGINT 30m python3 main.py':

    1006866.984229      task-clock (msec)         #    0.410 CPUs utilized          
         9,760,921      context-switches          #    0.010 M/sec                  
         2,192,035      cpu-migrations            #    0.002 M/sec                  
       562,808,556      page-faults               #    0.559 M/sec                  
 6,209,726,249,661      cycles                    #    6.167 GHz                    
 5,162,750,284,928      instructions              #    0.83  insn per cycle         
 1,069,215,976,191      branches                  # 1061.924 M/sec                  
    24,682,049,579      branch-misses             #    2.31% of all branches        

    2457.823307166 seconds time elapsed

