Exception ignored in: <bound method MinionSol.__del__ of <minion.MinionSol object at 0x2b26373f2fd0>>
Traceback (most recent call last):
  File "/home/pventura/relationaldef/minion.py", line 136, in __del__
    if not self.EOF:
AttributeError: 'MinionSol' object has no attribute 'EOF'
Spectrum = [3, 2, 1]
CANCELLED

State before abort: 
  Diversity = 9512
    1-diversity = 4
    2-diversity = 136
    3-diversity = 9372
  #Auts = 131
  #Isos = 2904
  1675336 calls to Minion

 Performance counter stats for 'timeout --signal=SIGINT 90m python3 ../../relationaldef/main.py':

    4920681.106319      task-clock (msec)         #    0.911 CPUs utilized          
         8,906,940      context-switches          #    0.002 M/sec                  
         4,857,996      cpu-migrations            #    0.987 K/sec                  
       715,255,995      page-faults               #    0.145 M/sec                  
12,612,356,952,618      cycles                    #    2.563 GHz                    
 9,264,405,686,294      instructions              #    0.73  insn per cycle         
 1,899,843,680,770      branches                  #  386.094 M/sec                  
    33,985,191,028      branch-misses             #    1.79% of all branches        

    5400.237937614 seconds time elapsed

