Exception ignored in: <bound method MinionSol.__del__ of <minion.MinionSol object at 0x2b311e4dec18>>
Traceback (most recent call last):
  File "/home/pventura/relationaldef/minion.py", line 136, in __del__
    if not self.EOF:
AttributeError: 'MinionSol' object has no attribute 'EOF'
Spectrum = [3, 2, 1]
CANCELLED

State before abort: 
  Diversity = 9488
    1-diversity = 4
    2-diversity = 136
    3-diversity = 9348
  #Auts = 144
  #Isos = 3412
  1837792 calls to Minion

 Performance counter stats for 'timeout --signal=SIGINT 90m python3 ../../relationaldef/main.py':

    4923061.761377      task-clock (msec)         #    0.912 CPUs utilized          
         9,801,399      context-switches          #    0.002 M/sec                  
         5,389,489      cpu-migrations            #    0.001 M/sec                  
       798,276,120      page-faults               #    0.162 M/sec                  
12,615,925,169,534      cycles                    #    2.563 GHz                    
10,072,480,984,929      instructions              #    0.80  insn per cycle         
 2,066,864,291,910      branches                  #  419.833 M/sec                  
    36,783,477,693      branch-misses             #    1.78% of all branches        

    5400.236739571 seconds time elapsed

