Exception ignored in: <bound method MinionSol.__del__ of <minion.MinionSol object at 0x2b5fc8e69d68>>
Traceback (most recent call last):
  File "/home/pventura/relationaldef/minion.py", line 132, in __del__
    if not self.EOF:
AttributeError: 'MinionSol' object has no attribute 'EOF'
Spectrum = [3, 2, 1]
CANCELLED

State before abort: 
  Diversity = 6211
    1-diversity = 4
    2-diversity = 130
    3-diversity = 6077
  #Auts = 6304
  #Isos = 19849
  923205 calls to Minion

 Performance counter stats for 'timeout --signal=SIGINT 45m python3 ../../main.py':

    1038809.138111      task-clock (msec)         #    0.385 CPUs utilized          
         6,215,233      context-switches          #    0.006 M/sec                  
         1,550,281      cpu-migrations            #    0.001 M/sec                  
       397,940,825      page-faults               #    0.383 M/sec                  
 5,402,535,384,837      cycles                    #    5.201 GHz                    
 4,527,313,277,648      instructions              #    0.84  insn per cycle         
   936,569,449,490      branches                  #  901.580 M/sec                  
    17,321,285,212      branch-misses             #    1.85% of all branches        

    2700.136122933 seconds time elapsed

