Exception ignored in: <bound method MinionSol.__del__ of <minion.MinionSol object at 0x2b0a38e539b0>>
Traceback (most recent call last):
  File "/home/pventura/relationaldef/minion.py", line 132, in __del__
    if not self.EOF:
AttributeError: 'MinionSol' object has no attribute 'EOF'
Spectrum = [3, 2, 1]
CANCELLED

State before abort: 
  Diversity = 7036
    1-diversity = 4
    2-diversity = 124
    3-diversity = 6908
  #Auts = 7153
  #Isos = 22765
  1159172 calls to Minion

 Performance counter stats for 'timeout --signal=SIGINT 45m python3 ../../main.py':

     991643.915388      task-clock (msec)         #    0.367 CPUs utilized          
         7,901,603      context-switches          #    0.008 M/sec                  
         1,873,499      cpu-migrations            #    0.002 M/sec                  
       503,940,437      page-faults               #    0.508 M/sec                  
 6,707,579,133,958      cycles                    #    6.764 GHz                    
 5,906,922,943,423      instructions              #    0.88  insn per cycle         
 1,220,150,033,564      branches                  # 1230.432 M/sec                  
    21,556,779,049      branch-misses             #    1.77% of all branches        

    2700.161918075 seconds time elapsed

