Exception ignored in: <bound method MinionSol.__del__ of <minion.MinionSol object at 0x2ab5cb810a90>>
Traceback (most recent call last):
  File "/home/pventura/relationaldef/minion.py", line 136, in __del__
    if not self.EOF:
AttributeError: 'MinionSol' object has no attribute 'EOF'
Spectrum = [3, 2, 1]
CANCELLED

State before abort: 
  Diversity = 9201
    1-diversity = 4
    2-diversity = 133
    3-diversity = 9064
  #Auts = 130
  #Isos = 3110
  1752296 calls to Minion

 Performance counter stats for 'timeout --signal=SIGINT 90m python3 ../../relationaldef/main.py':

    4930234.357418      task-clock (msec)         #    0.913 CPUs utilized          
         9,317,508      context-switches          #    0.002 M/sec                  
         5,125,028      cpu-migrations            #    0.001 M/sec                  
       745,138,591      page-faults               #    0.151 M/sec                  
12,636,365,904,201      cycles                    #    2.563 GHz                    
 9,534,295,865,899      instructions              #    0.75  insn per cycle         
 1,957,076,267,916      branches                  #  396.954 M/sec                  
    35,166,150,000      branch-misses             #    1.80% of all branches        

    5400.236570711 seconds time elapsed

