Exception ignored in: <bound method MinionSol.__del__ of <minion.MinionSol object at 0x2b04b7f0a8d0>>
Traceback (most recent call last):
  File "/home/pventura/relationaldef/minion.py", line 136, in __del__
    if not self.EOF:
AttributeError: 'MinionSol' object has no attribute 'EOF'
Spectrum = [3, 2, 1]
CANCELLED

State before abort: 
  Diversity = 6774
    1-diversity = 4
    2-diversity = 104
    3-diversity = 6666
  #Auts = 183
  #Isos = 12751
  2010771 calls to Minion

 Performance counter stats for 'timeout --signal=SIGINT 90m python3 ../../relationaldef/main.py':

    4830916.759115      task-clock (msec)         #    0.895 CPUs utilized          
        11,121,380      context-switches          #    0.002 M/sec                  
         5,841,661      cpu-migrations            #    0.001 M/sec                  
       837,992,618      page-faults               #    0.173 M/sec                  
12,378,696,737,471      cycles                    #    2.562 GHz                    
 9,088,277,138,722      instructions              #    0.73  insn per cycle         
 1,871,323,306,645      branches                  #  387.364 M/sec                  
    38,224,197,901      branch-misses             #    2.04% of all branches        

    5400.157772690 seconds time elapsed

