Exception ignored in: <bound method MinionSol.__del__ of <minion.MinionSol object at 0x2b09522cfa20>>
Traceback (most recent call last):
  File "/home/pventura/relationaldef/minion.py", line 132, in __del__
    if not self.EOF:
AttributeError: 'MinionSol' object has no attribute 'EOF'
Spectrum = [3, 2, 1]
CANCELLED

State before abort: 
  Diversity = 6819
    1-diversity = 4
    2-diversity = 135
    3-diversity = 6680
  #Auts = 6924
  #Isos = 21257
  953989 calls to Minion

 Performance counter stats for 'timeout --signal=SIGINT 45m python3 ../../main.py':

    1773642.000787      task-clock (msec)         #    0.657 CPUs utilized          
         5,816,150      context-switches          #    0.003 M/sec                  
         1,519,129      cpu-migrations            #    0.857 K/sec                  
       422,144,298      page-faults               #    0.238 M/sec                  
 5,581,088,204,954      cycles                    #    3.147 GHz                    
 5,384,140,574,843      instructions              #    0.96  insn per cycle         
 1,115,327,171,893      branches                  #  628.834 M/sec                  
    19,340,720,642      branch-misses             #    1.73% of all branches        

    2700.109155134 seconds time elapsed

