Exception ignored in: <bound method MinionSol.__del__ of <minion.MinionSol object at 0x2b0b1e5200f0>>
Traceback (most recent call last):
  File "/home/pventura/relationaldef/minion.py", line 136, in __del__
    if not self.EOF:
AttributeError: 'MinionSol' object has no attribute 'EOF'
Spectrum = [3, 2, 1]
CANCELLED

State before abort: 
  Diversity = 8619
    1-diversity = 4
    2-diversity = 120
    3-diversity = 8495
  #Auts = 192
  #Isos = 7590
  2053432 calls to Minion

 Performance counter stats for 'timeout --signal=SIGINT 90m python3 ../../relationaldef/main.py':

    5282120.236626      task-clock (msec)         #    0.978 CPUs utilized          
        10,035,996      context-switches          #    0.002 M/sec                  
         3,900,835      cpu-migrations            #    0.738 K/sec                  
       851,239,829      page-faults               #    0.161 M/sec                  
13,084,177,599,186      cycles                    #    2.477 GHz                    
 9,997,393,695,257      instructions              #    0.76  insn per cycle         
 2,054,189,236,070      branches                  #  388.895 M/sec                  
    40,357,825,034      branch-misses             #    1.96% of all branches        

    5400.167204993 seconds time elapsed

