Exception ignored in: <bound method Popen.__del__ of <subprocess.Popen object at 0x2b611a7dee80>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/subprocess.py", line 731, in __del__
    _active.append(self)
KeyboardInterrupt
Spectrum = [3, 2, 1]
DEFINABLE

Final state: 
  Diversity = 12665
    1-diversity = 4
    2-diversity = 131
    3-diversity = 12530
  #Auts = 226
  #Isos = 8204
  3997856 calls to Minion

 Performance counter stats for 'timeout --signal=SIGINT 90m python3 ../../relationaldef/main.py':

   11524958.829389      task-clock (msec)         #    0.916 CPUs utilized          
        21,265,638      context-switches          #    0.002 M/sec                  
        11,753,402      cpu-migrations            #    0.001 M/sec                  
     1,666,616,793      page-faults               #    0.145 M/sec                  
29,550,881,344,233      cycles                    #    2.564 GHz                    
21,076,326,837,088      instructions              #    0.71  insn per cycle         
 4,309,936,061,776      branches                  #  373.965 M/sec                  
    76,953,451,201      branch-misses             #    1.79% of all branches        

   12575.334254986 seconds time elapsed

